/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package avltrees.rdc5.ui;

import avltrees.rdc5.AVLTree;
import avltrees.rdc5.Subject;
import javax.swing.JOptionPane;

/**
 *
 * @author japso
 */
public class UI extends javax.swing.JFrame {

    AVLTree avl = new AVLTree();
    
    public UI() {
        initComponents();
        avl.loadFile();
        this.setTitle("Materias ISC");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtClave = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtNombre = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JLabel();
        txtRama = new javax.swing.JLabel();
        txtProfesor = new javax.swing.JLabel();
        txtGrupos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar clave");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtDescripcion))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtRama))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtProfesor))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtGrupos)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(38, 38, 38)
                .addComponent(txtNombre)
                .addGap(18, 18, 18)
                .addComponent(txtDescripcion)
                .addGap(18, 18, 18)
                .addComponent(txtRama)
                .addGap(18, 18, 18)
                .addComponent(txtProfesor)
                .addGap(18, 18, 18)
                .addComponent(txtGrupos)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String id = this.txtClave.getText().trim();
        
        Subject sub = avl.find(id);
        
        if(sub == null) {
            JOptionPane.showMessageDialog(this, "No se encontro ninguna materia con esa clave");
            this.txtNombre.setText("");
            this.txtDescripcion.setText("");
            this.txtRama.setText("");
            this.txtProfesor.setText("");
            this.txtGrupos.setText("");
        }
        else {
            this.txtNombre.setText("Nombre de la materia: "+sub.getName());
            this.txtDescripcion.setText("Descripcion de la materia: "+sub.getDescription());
            this.txtRama.setText("Rama de aprendizaje: "+sub.getBranch());
            this.txtProfesor.setText("Profesor que imparte la materia: "+sub.getProfessor());
            this.txtGrupos.setText("Grupos disponibles: "+sub.getAvailability());
        }
            
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JTextField txtClave;
    private javax.swing.JLabel txtDescripcion;
    private javax.swing.JLabel txtGrupos;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtProfesor;
    private javax.swing.JLabel txtRama;
    // End of variables declaration//GEN-END:variables
}
